eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:postgresql://user_db:5432/userdb
    driverClassName: org.postgresql.Driver
    username: root
    password: Naul126@.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
